live_config_reload = true

[font]
size = 13.0

[font.normal]
family = "Fira Code"

[[keyboard.bindings]]
chars = "\u001BF"
key = "Right"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001BB"
key = "Left"
mods = "Alt"

[[keyboard.bindings]]
action = "CreateNewWindow"
key = "N"
mods = "Command"

[shell]
args = ["-i"]
program = "/bin/zsh"
