# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

[kubernetes]
format = 'on [⛵ $context \($namespace\)](dimmed green) '
disabled = false
[kubernetes.context_aliases]
"dev.local.cluster.k8s" = "dev"
"gke_.*_(?P<cluster>[\\w-]+)" = "gke-$cluster"
"gke_(?P<project>[\\w-]+)_(?P<location>[\\w-]+)_(?P<cluster>[\\w-]+)" =  "[$project][$cluster]"

