on:
  pull_request:

jobs:
  lints:
    name: Build
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main
      - name: Add User `edude03`
        run: |
          useradd edude03
      - name: Run `Home Manager`
        run: sudo -u edude03 -i nix run home-manager -- switch
